name: Deploy to Heroku

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronized]

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Create build
        run: npm run build

      - name: Push to heroku
        uses: akhileshns/heroku-deploy@79ef2ae4ff9b897010907016b268fd0f88561820
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: 'cv-tretton37'
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          buildpack: https://github.com/mars/create-react-app-buildpack.git